Frontends/Web/src/BusinessSolutions.Web.UI/Pages/AddItem.cshtml.cs
using BusinessSolutions.Web.Application.ViewModels;
using BusinessSolutions.Web.Application.Common.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BusinessSolutions.Web.UI.Pages
{
    public class AddItemModel : PageModel
    {
        [BindProperty(SupportsGet = true)]
        public string? Order { get; set; }

        [BindProperty(SupportsGet = true)]
        public string? Item { get; set; }

        [BindProperty]
        public ItemViewModel NewItem { get; set; } = new();

        public IActionResult OnGetAsync()
        {
            if (Item is not null)
            {
                var orderItem = Item.Deserialize(new ItemViewModel());
                if (orderItem is not null)
                {
                    NewItem = orderItem;
                }
            }

            return Page();
        }

        public IActionResult OnPostAsync()
        {
            if (ModelState.IsValid && !string.IsNullOrEmpty(Order))
            {
                var order = Order.Deserialize(new OrderViewModel()) ?? new();

                if (Item is not null)
                {
                    var orderItem = Item.Deserialize(new ItemViewModel());
                    if (orderItem is not null)
                    {
                        order.RemoveItem(orderItem);
                    }
                }
                
                order.AddItem(NewItem);
                return RedirectToPage("CreateOrder", new { order = order.Serialize() });
            }
            return Page();
        }
    }
}

Frontends/Web/src/BusinessSolutions.Web.UI/Pages/CreateOrder.cshtml.cs
using AutoMapper;
using BusinessSolutions.Web.Application.ViewModels;
using BusinessSolutions.Web.Application.Common.Extensions;
using BusinessSolutions.Web.Application.Items.Commands.CreateItem;
using BusinessSolutions.Web.Application.Items.Commands.UpdateItem;
using BusinessSolutions.Web.Application.Orders.Commands.CreateOrder;
using BusinessSolutions.Web.Application.Orders.Commands.UpdateOrder;
using BusinessSolutions.Web.Application.Orders.Queries.GetOrder;
using BusinessSolutions.Web.Application.Providers.Queries.GetProviders;
using BusinessSolutions.Web.Domain.Models;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BusinessSolutions.Web.UI.Pages
{
    public class CreateOrderModel : PageModel
    {
        private readonly IMediator _mediator;
        private readonly IMapper _mapper;

        public CreateOrderModel(IMediator mediator, IMapper mapper)
        {
            _mediator = mediator;
            _mapper = mapper;
        }

        [BindProperty]
        public OrderViewModel Order { get; set; } = new();

        public List<Provider> Providers { get; set; } = new();

        public async Task<IActionResult> OnGetAsync(string? number, string? order)
        {
            if (number is not null) {
                var response = await _mediator.Send(new GetOrderQuery { Number = number });
                if (response is not null) {
                    Order = _mapper.Map<OrderViewModel>(response);
                }
            }
            else if (!string.IsNullOrEmpty(order)) {
                Order = order.Deserialize(Order) ?? new();
            }
            await GetProviders();
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid) {
                if (string.IsNullOrEmpty(Order.Number)) {
                    var order = _mapper.Map<CreateOrderCommand>(Order);
                    var response = await _mediator.Send(order);
                    if (response != null) {
                        foreach (var item in Order.Items!)
                        {
                            var createItem = _mapper.Map<CreateItemCommand>(item);
                            createItem.OrderId = response.Id;
                            await _mediator.Send(createItem);
                        }
                        TempData["message"] = $"Order \"{response.Number}\" Created";
                    }
                    else {
                        TempData["message"] = "Error Creating Order";
                    }
                }
                else {
                    var order = _mapper.Map<UpdateOrderCommand>(Order);
                    var response = await _mediator.Send(order);
                    if (response != null) {
                        foreach (var item in Order.Items!)
                        {
                            if (item.ItemId == default)
                            {
                                var createItem = _mapper.Map<CreateItemCommand>(item);
                                createItem.OrderId = response.Id;
                                await _mediator.Send(createItem);
                            }
                            else
                            {
                                var updateItem = _mapper.Map<UpdateItemCommand>(item);
                                await _mediator.Send(updateItem);
                            }
                        }
                        TempData["message"] = $"Order \"{response.Number}\" Updated";
                    }
                    else {
                        TempData["message"] = "Error Updating Order";
                    }
                };
                RedirectToPage();
            }
            await GetProviders();
            return Page();
        }

        public IActionResult OnPostAddItemAsync()
        {
            return RedirectToPage("AddItem", new { order = Order.Serialize() });
        }

        public IActionResult OnPostEditItemAsync(string item)
        {
            return RedirectToPage("AddItem", new { order = Order.Serialize(), item });
        }

        public IActionResult OnPostRemoveItemAsync(string item)
        {
            var orderItem = item.Deserialize(new ItemViewModel());
            if (orderItem is not null) {
                Order.RemoveItem(orderItem);
            }
            return RedirectToPage(new { order = Order.Serialize() });
        }

        private async Task GetProviders()
        {
            string? providerData = TempData["providers"] as string;
            if (providerData is not null) {
                var cached = providerData.Deserialize(Providers);
                if (cached is not null) {
                    Providers = cached;
                    return;
                }
            }
            var response = await _mediator.Send(new GetProvidersWithPaginationQuery { PageSize = int.MaxValue });                
            if (response is not null) {
                Providers = response.Data.ToList();
                TempData["providers"] = Providers.Serialize();
            }
            else {
                TempData["message"] = "Error Retrieving Providers";
            }
        }
    }
}

Frontends/Web/src/BusinessSolutions.Web.UI/Pages/CreateProvider.cshtml.cs
using AutoMapper;
using BusinessSolutions.Web.Application.ViewModels;
using BusinessSolutions.Web.Application.Providers.Commands.CreateProvider;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BusinessSolutions.Web.UI.Pages
{
    public class CreateProviderModel : PageModel
    {
        private readonly IMediator _mediator;
        private readonly IMapper _mapper;

        public CreateProviderModel(IMediator mediator, IMapper mapper) 
        {
            _mediator = mediator;
            _mapper = mapper;
        }

        public ProviderViewModel Provider { get; set; } = new();

        public async Task<IActionResult> OnPostAsync(
            [FromForm(Name = "Provider")] ProviderViewModel target)
        {
            if (ModelState.IsValid)
            {
                var provider = _mapper.Map<CreateProviderCommand>(target);
                var result = await _mediator.Send(provider);
                if (result > 0)
                {
                    TempData["message"] = "Provider Created";
                }
                else 
                {
                    TempData["message"] = "Error Creating Provider";
                }
                return RedirectToPage();
            }
            return Page();
        }
    }
}

Frontends/Web/src/BusinessSolutions.Web.UI/Pages/Index.cshtml.cs
using AutoMapper;
using BusinessSolutions.Web.Application.Orders.Queries.GetOrders;
using BusinessSolutions.Web.Application.Providers.Queries.GetProviders;
using BusinessSolutions.Web.Application.ViewModels;
using MediatR;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BusinessSolutions.Web.UI.Pages
{
    public class IndexModel : PageModel
    {
        private readonly IMediator mediator;
        private readonly IMapper mapper;

        public IndexModel(IMediator mediator, IMapper mapper)
        {
            this.mediator = mediator;
            this.mapper = mapper;
        }

        public int ProvidersNumber { get; set; }

        public int OrdersNumber { get; set; }

        public async Task OnGetAsync()
        {
            var providers = await mediator.Send(new GetProvidersWithPaginationQuery());
            ProvidersNumber = providers.Data.Count();

            var orders = await mediator.Send(new GetOrdersWithPaginationQuery());
            OrdersNumber = orders.Data.Count();
        }
    }
}

Frontends/Web/src/BusinessSolutions.Web.UI/Pages/SelectOrder.cshtml.cs
using AutoMapper;
using BusinessSolutions.Web.Application.Common.Models;
using BusinessSolutions.Web.Application.Items.Commands.UpdateItem;
using BusinessSolutions.Web.Application.Orders.Commands.DeleteOrder;
using BusinessSolutions.Web.Application.Orders.Commands.UpdateOrder;
using BusinessSolutions.Web.Application.Orders.Queries.GetOrders;
using BusinessSolutions.Web.Application.Providers.Queries.GetProviders;
using BusinessSolutions.Web.Domain.Models;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using BusinessSolutions.Web.Application.ViewModels;
using BusinessSolutions.Web.Application.Common.Extensions;

namespace BusinessSolutions.Web.UI.Pages
{
    public class SelectOrderModel : PageModel
    {
        private readonly IMediator _mediator;
        private readonly IMapper _mapper;

        public SelectOrderModel(IMediator mediator, IMapper mapper)
        {
            _mediator = mediator;
            _mapper = mapper;
        }

        public List<Order> Orders { get; set; } = new();

        public List<Provider> Providers { get; set; } = new();

        [BindProperty]
        public FilterViewModel Filter { get; set; } = new();

        public bool AnyFilter
        {
            get => Filter.GetType().GetProperties()
                .Select(p => p.GetValue(Filter)?.ToString())
                .Any(value => !string.IsNullOrEmpty(value));
        }

        public async Task OnGetAsync()
        {
            if (!AnyFilter && TempData.ContainsKey("filter"))
            {
                GetFilter();
            }
            await GetProviders();
            await GetOrders();
        }

        public async Task<IActionResult> OnPostAsync(string? id, string? task)
        {
            TempData["id"] = id;
            TempData["task"] = task;
            TempData["modal"] = true;

            GetFilter();
            await GetOrders();

            return RedirectToPage(new { Filter });
        }

        public IActionResult OnPostFilter()
        {
            TempData["filter"] = Filter.Serialize();
            return RedirectToPage();
        }

        public IActionResult OnPostClear()
        {
            Filter = new();
            TempData.Remove("filter");
            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostEditAsync(
            [FromForm] OrderViewModel order)
        {
            if (ModelState.IsValid)
            {
                var command = _mapper.Map<UpdateOrderCommand>(order);
                var response = await _mediator.Send(command);
                if (response != null)
                {
                    foreach (var item in order.Items!)
                    {
                        var updateItem = _mapper.Map<UpdateItemCommand>(item);
                        await _mediator.Send(updateItem);
                    }
                    TempData["message"] = $"Order \"{order.Number}\" Updated";
                }
                else
                {
                    TempData["message"] = "Error Updating Order";
                }
                return RedirectToPage();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostDeleteAsync([FromForm] Order order)
        {
            await _mediator.Send(new DeleteOrderCommand { Number = order.Number });
            TempData["message"] = $"Order \"{order.Number}\" Deleted";
            TempData.Remove("orders");
            return RedirectToPage();
        }

        private void GetFilter()
        {
            string? filterData = TempData["filter"] as string;
            if (filterData is not null)
            {
                Filter = filterData.Deserialize(Filter) ?? new();
            }
        }

        private async Task GetProviders()
        {
            string? providerData = TempData["providers"] as string;
            if (providerData is not null)
            {
                var cached = providerData.Deserialize(Providers);
                if (cached is not null)
                {
                    Providers = cached;
                    return;
                }
            }
            var response = await _mediator.Send(new GetProvidersWithPaginationQuery { PageSize = int.MaxValue });
            if (response is not null)
            {
                Providers = response.Data.ToList();
                TempData["providers"] = Providers.Serialize();
            }
            else
            {
                TempData["message"] = "Error Retrieving Providers";
            }
        }

        private async Task GetOrders(bool cache = false)
        {
            if (cache)
            {
                string? orderData = TempData["orders"] as string;
                if (orderData is not null)
                {
                    var p = orderData.Deserialize(Orders);
                    if (p is not null)
                    {
                        Orders = p;
                        return;
                    }
                }
            }

            PaginatedList<Order> response;

            if (AnyFilter)
            {
                var query = _mapper.Map<GetOrdersByFilterQuery>(Filter);
                query.PageSize = int.MaxValue;

                response = await _mediator.Send(query);
            }
            else
            {
                var query = new GetOrdersWithPaginationQuery { PageSize = int.MaxValue };

                response = await _mediator.Send(query);
            }

            if (response is not null)
            {
                Orders = response.Data.OrderBy(x => x.Date).ToList();
                TempData["orders"] = Orders.Serialize();
            }
            else
            {
                TempData["message"] = "Error Retrieving Orders";
            }
        }
    }
}

Frontends/Web/src/BusinessSolutions.Web.UI/Pages/AddItem.cshtml
@page
@model AddItemModel
@{
    ViewBag.Workflow = "CreateOrder";
}

<form method="post">
    <input type="hidden" asp-for=Order />
    <input type="hidden" asp-for=Item />
    <div class="form-group my-2">
        <label asp-for="NewItem.Name"></label>
        <div>
            <span asp-validation-for="NewItem.Name" class="text-warning"></span>
        </div>
        <input asp-for="NewItem.Name" class="form-control" />
    </div>
    <div class="form-group my-2">
        <label asp-for="NewItem.Quantity"></label>
        <input asp-for="NewItem.Quantity" type="number" min="1" value="1" class="form-control" />
    </div>
    <div class="form-group my-2">
        <label asp-for="NewItem.Unit"></label>
        <div>
            <span asp-validation-for="NewItem.Unit" class="text-warning"></span>
        </div>
        <input asp-for="NewItem.Unit" class="form-control" />
    </div>
    <div class="mt-3">
        <button type="submit" class="btn btn-success">Add</button>
        <a asp-page="CreateOrder" asp-route-order=@Model.Order class="btn btn-secondary">Cancel</a>
    </div>
</form>

Frontends/Web/src/BusinessSolutions.Web.UI/Pages/CreateOrder.cshtml
@page
@model CreateOrderModel
@{
    var newOrder = string.IsNullOrEmpty(Model.Order.Number);
    ViewBag.Workflow = newOrder ? "CreateOrder" : "EditOrder";
    var cancelPage = newOrder ? "CreateOrder" : "SelectOrder";
}
@if (TempData.ContainsKey("message"))
{
    <div class="alert alert-success">@TempData["message"]</div>
}
<form method="post" id="order">
    <div class="form-group my-2">
        <label asp-for="Order.Provider"></label>
        <select asp-for="Order.ProviderId"
                asp-items="@(new SelectList(Model?.Providers, nameof(Provider.ProviderId), nameof(Provider.ProviderName), Model?.Order.ProviderId))">
            <option value=0>Please select one</option>
        </select>
        <div>
            <span asp-validation-for="Order.ProviderId" class="text-warning"></span>
        </div>
    </div>
    <button asp-page-handler="AddItem" class="btn btn-primary">
        Add Item
    </button>
    <div>
        <span asp-validation-for="Order.Items" class="text-warning"></span>
    </div>
    @if (Model?.Order.Items?.Any() ?? false) {
        <fieldset>
            <legend>Order Items:</legend>
            <table class="table table-sm table-striped table-bordered">
                <thead>
                    <tr><th>Name</th><th>Quantity</th><th>Unit</th><th /></tr>
                </thead>
                <tbody>

                    @for (int i = 0; i < Model?.Order.Items.Count(); i++)
                    {
                        <tr>
                            <input asp-for="Order.Items[i].ItemId" type="hidden">
                            <td>
                                <input asp-for="Order.Items[i].Name">
                            </td>
                            <td>
                                <input asp-for="Order.Items[i].Quantity" type="number" min="1">
                                
                            </td>
                            
                            <td>
                                <input asp-for="Order.Items[i].Unit">
                                
                            </td>
                            <td>            
                                <button class="btn btn-sm btn-danger" asp-page-handler="RemoveItem" asp-route-item=@Model?.Order.Items[i].Serialize() >
                                    Remove
                                </button>
                            </td>   
                        </tr>
                        <div>
                            <span asp-validation-for="Order.Items[i].Name" class="text-warning"></span>
                            <span asp-validation-for="Order.Items[i].Quantity" class="text-warning"></span>
                            <span asp-validation-for="Order.Items[i].Unit" class="text-warning"></span>
                        </div>
                    }
                </tbody>
            </table>
        </fieldset>
    }
    <input type="hidden" asp-for="Order.Id"/>
    <input type="hidden" asp-for="Order.Number" />
    <div class="mt-3">
        <button type="submit" form="order" class="btn btn-success">@(newOrder ? "Create" : "Edit")</button>
        <a asp-page=@cancelPage class="btn btn-secondary">Cancel</a>
    </div>
</form>

Frontends/Web/src/BusinessSolutions.Web.UI/Pages/CreateProvider.cshtml
@page
@model CreateProviderModel
@{
    ViewBag.Workflow = "CreateProvider";
}
@if (TempData.ContainsKey("message"))
{
    <div class="alert alert-success">@TempData["message"]</div>
}
<form method="post">
    <div class="form-group my-2">
        <label asp-for="Provider.ProviderName"></label>
        <div>
            <span asp-validation-for="Provider.ProviderName" class="text-warning"></span>
        </div>
        <input asp-for="Provider.ProviderName" class="form-control" />
    </div>
    <div class="mt-3">
        <button type="submit" class="btn btn-success">Create</button>
        <a asp-page="CreateProvider" class="btn btn-secondary">Cancel</a>
    </div>
</form>

Frontends/Web/src/BusinessSolutions.Web.UI/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewBag.Workflow = "Overview";
}

<h4 class="bg-success text-white text-center p-2 m-2">Overview</h4>
<div class="text-center">
    <h5 class="p-2">
        The catalog contains @Model?.ProvidersNumber providers and @Model?.OrdersNumber orders.
    </h5>
</div>

Frontends/Web/src/BusinessSolutions.Web.UI/Pages/SelectOrder.cshtml
@page
@model SelectOrderModel
@{
    ViewBag.Workflow = "SelectOrder";
    var modal = TempData["modal"] as bool? ?? HttpContext.Request.Query["task"] == "View";
    var task = TempData["Task"]?.ToString();
    var orderNumber = TempData["id"]?.ToString();
    TempData["orders"] = Model.Orders?.Serialize();
    TempData["filter"] = Model.Filter?.Serialize();
}
@if (TempData.ContainsKey("message"))
{
    <div class="alert alert-success">@TempData["message"]</div>
}

<form method="post" asp-page-handler="filter" class="my-2">
    <input type="hidden" name="modal" value="@modal" />
    <div class="form-group row my-2">
        <div class="col-sm-6">
            <label asp-for="Filter.StartDate"></label>
            <input asp-for="Filter.StartDate" type="date" class="form-control" />
        </div>
        <div class="col-sm-6">
            <label asp-for="Filter.EndDate"></label>
            <input asp-for="Filter.EndDate" type="date" class="form-control" />
        </div>
    </div>
    <div class="form-group row my-2">
        <div class="col-sm-6">
            <label asp-for="Filter.ProviderId"></label>
            <input asp-for="Filter.ProviderId" class="form-control" />
        </div>
        <div class="col-sm-6">
            <label asp-for="Filter.ProviderName"></label>
            <input asp-for="Filter.ProviderName" class="form-control" />
        </div>
    </div>
    <div class="form-group row my-2">
        <div class="col-sm-6">
            <label asp-for="Filter.ItemName"></label>
            <input asp-for="Filter.ItemName" class="form-control" />
        </div>
        <div class="col-sm-6">
            <label asp-for="Filter.ItemUnit"></label>
            <input asp-for="Filter.ItemUnit" class="form-control" />
        </div>
    </div>
    <div class="form-group row my-2">
        <div class="col-sm-6">
            <label asp-for="Filter.OrderNumber"></label>
            <input asp-for="Filter.OrderNumber" class="form-control" />
        </div>
        <div class="col-sm-6 text-center mt-2">
            <button class="btn btn-success px-2 m-2">
                Filter
            </button>
            <button form="clear" class="btn btn-info px-2 m-2">
                Clear
            </button>
        </div>
    </div>
</form>
<form id="clear" method="post" asp-page-handler="clear">
</form>
<table class="table table-sm table-striped table-bordered my-3">
    <thead>
        <tr>
            <th>Order</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Orders?.Count() == 0)
        {
            <tr><td colspan="2">No matches</td></tr>
        }
        else if (Model.Orders?.Count() > 0)
        {
            @foreach (Order r in Model.Orders)
            {
                <tr>
                    <td>@r.Number</td>
                    <td class="text-center">
                        <form method="post">
                            <input type="hidden" name="id" value="@r.Id" />
                            <button class="btn btn-sm btn-info" asp-route-task="View">
                                View
                            </button>
                            <button class="btn btn-sm btn-danger" asp-route-task="Delete">
                                Delete
                            </button>
                            <button class="btn btn-sm btn-warning" asp-route-task="Edit">
                                Edit
                            </button>
                            <a class="btn btn-sm btn-secondary" asp-page="CreateOrder" asp-route-number="@r.Number">
                                Add/Remove
                            </a>
                        </form>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

<div class="modal fade" id="orderModal" tabindex="-1" data-bs-backdrop="static" aria-labelledby="order" aria-hidden="true">
    <vc:order-editor task=@task id=@orderNumber />
</div>

<script src="/lib/jquery/jquery.js"></script>
<script type="text/javascript">
    "use strict";
    if (window.addEventListener) { // Mozilla, Netscape, Firefox
        window.addEventListener('load', WindowLoad, false);
    } else if (window.attachEvent) { // IE
        window.attachEvent('onload', WindowLoad);
    }
    const modal = document.querySelector('input[name="modal"]');
    function WindowLoad(event) {
        if (modal.value) {
            $("#orderModal").modal('show');
        }
    }
    $("#orderModal").on("hidden.bs.modal", function () {  
        $(this)
            .find("input,textarea,select")
               .val('')
               .end()
            .find("input[type=checkbox], input[type=radio]")
               .prop("checked", "")
               .end();
    });
</script>

Frontends/Web/src/BusinessSolutions.Web.UI/Pages/SelectProvider.cshtml
@page
@model SelectProvider
@{
    ViewBag.Workflow = "SelectProvider";
    var modal = TempData["modal"] as bool? ?? HttpContext.Request.Query["task"] == "Create";
    var task = TempData["Task"]?.ToString();
    int.TryParse(TempData["id"]?.ToString(), out int providerId);
    TempData["providers"] = System.Text.Json.JsonSerializer.Serialize(Model.Providers);
}
@if (TempData.ContainsKey("message"))
{
    <div class="alert alert-success">@TempData["message"]</div>
}
<input type="hidden" name="modal" value="@modal" />
<a class="btn btn-primary float-end m-2" asp-page="" asp-route-task="Create">
    Create
</a>
<table class="table table-sm table-striped table-bordered">
    <thead>
        <tr>
            <th>Provider</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Providers?.Count() == 0)
        {
            <tr><td colspan="2">No matches</td></tr>
        }
        else if (Model.Providers?.Count() > 0)
        {
            @foreach (Provider p in Model.Providers)
            {
                <tr>
                    <td>@p.ProviderName</td>
                    <td class="text-center">
                    <form method="post">
                        <input type="hidden" name="id" value="@p.ProviderId" />
                        <button class="btn btn-sm btn-danger" asp-route-task="Delete">
                            Delete
                        </button>
                    </form>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

<div class="modal fade" id="providerModal" tabindex="-1" data-bs-backdrop="static" aria-labelledby="provider" aria-hidden="true">
    <vc:provider-editor task=@task id=@providerId />
</div>

<script src="/lib/jquery/jquery.js"></script>
<script type="text/javascript">
    "use strict";
    if (window.addEventListener) { // Mozilla, Netscape, Firefox
        window.addEventListener('load', WindowLoad, false);
    } else if (window.attachEvent) { // IE
        window.attachEvent('onload', WindowLoad);
    }
    const modal = document.querySelector('input[name="modal"]');
    function WindowLoad(event) {
        if (modal.value) {
            $("#providerModal").modal('show');
        }
    }
    $("#providerModal").on("hidden.bs.modal", function () {  
        $(this)
            .find("input,textarea,select")
               .val('')
               .end()
            .find("input[type=checkbox], input[type=radio]")
               .prop("checked", "")
               .end();
    });
</script>

Frontends/Web/src/BusinessSolutions.Web.UI/Pages/_Layout.cshtml
@{
    string theme = ViewData["theme"] as string ?? "primary";
    bool showNav = ViewData["showNav"] as bool? ?? true;
    string navPartial = ViewData["navPartial"] as string ?? "_Workflows";
    string? workflow = ViewData["workflow"] as string;
    string banner = ViewData["banner"] as string ?? "Dashboard";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Order Catalog</title>
    <link href="/lib/twitter-bootstrap/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-light navbar-expand-sm navbar-toggleable-sm border-bottom border-secondary box-shadow">
            <div class="container">
                <a class="navbar-brand" href="/">Order Catalog</a>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <h4 class="bg-@theme text-center text-white p-2">@banner</h4>
    <div class="my-2">
        <div class="container-fluid">
            <div class="row">
                @if (showNav)
                {
                    <div class="col-auto">
                        <partial name="@navPartial" model="@((workflow, theme))" />
                    </div>
                }
                <div class="col">
                    @RenderBody()
                </div>
            </div>
        </div>
    </div>
    <footer class="border-top border-secondary footer">
        <div class="container">
            &copy; @DateTime.Now.Year - Order Catalog
        </div>
    </footer>
    <script src="/lib/twitter-bootstrap/js/bootstrap.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Frontends/Web/src/BusinessSolutions.Web.UI/Pages/_Workflows.cshtml
@model (string workflow, string theme)
@{
    Func<string, string> getClass = (string feature) =>
        feature != null && feature.Equals(Model.workflow) ? "active" : "";
}

<div class="d-grid">
    <a class="btn btn-@Model.theme @getClass("Overview") my-1" asp-page="Index">
        Overview
    </a>
    <a class="btn btn-@Model.theme @getClass("CreateOrder") my-1" asp-page="CreateOrder">
        Create Order
    </a>
    <a class="btn btn-@Model.theme @getClass("SelectOrder") my-1" asp-page="SelectOrder">
        Orders
    </a>
    <a class="btn btn-@Model.theme @getClass("CreateProvider") my-1" asp-page="CreateProvider">
        Create Provider
    </a>
    <a class="btn btn-@Model.theme @getClass("SelectProvider") my-1" asp-page="SelectProvider">
        Providers
    </a>
</div>